spring.application.name=springboot-restapi
# Change the default server port from 8080 to 8090
server.port=8090
# Change the default context path from / to /restapi
server.servlet.context-path=/restapi
